[2025-04-13T23:43:45.599+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-13T23:43:45.654+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_garrafa_stanley.etl_scrap manual__2025-04-13T23:43:32.815041+00:00 [queued]>
[2025-04-13T23:43:45.667+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_garrafa_stanley.etl_scrap manual__2025-04-13T23:43:32.815041+00:00 [queued]>
[2025-04-13T23:43:45.668+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-13T23:43:45.688+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): etl_scrap> on 2025-04-13 23:43:32.815041+00:00
[2025-04-13T23:43:45.697+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2042) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-13T23:43:45.700+0000] {standard_task_runner.py:72} INFO - Started process 2044 to run task
[2025-04-13T23:43:45.700+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pipeline_garrafa_stanley', 'etl_scrap', 'manual__2025-04-13T23:43:32.815041+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpwqryp3i7']
[2025-04-13T23:43:45.703+0000] {standard_task_runner.py:105} INFO - Job 51: Subtask etl_scrap
[2025-04-13T23:43:45.805+0000] {task_command.py:467} INFO - Running <TaskInstance: pipeline_garrafa_stanley.etl_scrap manual__2025-04-13T23:43:32.815041+00:00 [running]> on host 5cb3b0b4f804
[2025-04-13T23:43:45.969+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline_garrafa_stanley' AIRFLOW_CTX_TASK_ID='etl_scrap' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T23:43:32.815041+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-13T23:43:32.815041+00:00'
[2025-04-13T23:43:45.971+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-13T23:43:46.005+0000] {logging_mixin.py:190} INFO - PostgreSQL error: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2025-04-13T23:43:46.006+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-13T23:43:46.027+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-13T23:43:46.028+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=pipeline_garrafa_stanley, task_id=etl_scrap, run_id=manual__2025-04-13T23:43:32.815041+00:00, execution_date=20250413T234332, start_date=20250413T234345, end_date=20250413T234346
[2025-04-13T23:43:46.118+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-13T23:43:46.156+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-13T23:43:46.160+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
