[2025-04-12T13:46:52.222+0000] {processor.py:186} INFO - Started process (PID=11227) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:46:52.224+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:46:52.227+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:46:52.227+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:46:52.238+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:46:52.236+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 17
    'start_date': datetime(2025,04,12)
                                ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2025-04-12T13:46:52.239+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:46:52.281+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.068 seconds
[2025-04-12T13:47:22.779+0000] {processor.py:186} INFO - Started process (PID=11291) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:47:22.783+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:47:22.788+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:47:22.788+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:47:22.801+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:47:22.799+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 17
    'start_date': datetime(2025,04,12)
                                ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2025-04-12T13:47:22.802+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:47:22.857+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.089 seconds
[2025-04-12T13:47:53.366+0000] {processor.py:186} INFO - Started process (PID=11355) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:47:53.368+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:47:53.372+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:47:53.371+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:47:53.380+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:47:53.379+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 17
    'start_date': datetime(2025,04,12)
                                ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2025-04-12T13:47:53.382+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:47:53.427+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.069 seconds
[2025-04-12T13:48:24.048+0000] {processor.py:186} INFO - Started process (PID=11419) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:48:24.055+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:48:24.062+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:48:24.061+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:48:24.076+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:48:24.074+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 17
    'start_date': datetime(2025,04,12)
                                ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2025-04-12T13:48:24.078+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:48:24.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.090 seconds
[2025-04-12T13:48:54.390+0000] {processor.py:186} INFO - Started process (PID=11485) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:48:54.392+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:48:54.396+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:48:54.396+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:48:54.407+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:48:54.405+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 17
    'start_date': datetime(2025,04,12)
                                ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2025-04-12T13:48:54.408+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:48:54.455+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.076 seconds
[2025-04-12T13:49:24.906+0000] {processor.py:186} INFO - Started process (PID=11548) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:49:24.908+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:49:24.912+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:49:24.912+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:49:24.923+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:49:24.921+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 17
    'start_date': datetime(2025,04,12)
                                ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2025-04-12T13:49:24.925+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:49:24.978+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.081 seconds
[2025-04-12T13:49:55.194+0000] {processor.py:186} INFO - Started process (PID=11613) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:49:55.196+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:49:55.201+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:49:55.200+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:49:55.210+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:49:55.208+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 17
    'start_date': datetime(2025,04,12)
                                ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2025-04-12T13:49:55.211+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:49:55.264+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.078 seconds
[2025-04-12T13:50:25.999+0000] {processor.py:186} INFO - Started process (PID=11677) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:50:26.001+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:50:26.006+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:50:26.006+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:50:26.023+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:50:26.019+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 17
    'start_date': datetime(2025,04,12)
                                ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2025-04-12T13:50:26.025+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:50:26.076+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.094 seconds
[2025-04-12T13:50:56.231+0000] {processor.py:186} INFO - Started process (PID=11739) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:50:56.234+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:50:56.241+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:50:56.240+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:50:56.258+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:50:56.255+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 17
    'start_date': datetime(2025,04,12)
                                ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2025-04-12T13:50:56.260+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:50:56.320+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.100 seconds
[2025-04-12T13:51:26.471+0000] {processor.py:186} INFO - Started process (PID=11805) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:51:26.473+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:51:26.477+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:51:26.477+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:51:26.487+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:51:26.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 17
    'start_date': datetime(2025,04,12)
                                ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2025-04-12T13:51:26.488+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:51:26.534+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.072 seconds
[2025-04-12T13:51:57.346+0000] {processor.py:186} INFO - Started process (PID=11869) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:51:57.347+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:51:57.350+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:51:57.350+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:51:57.359+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:51:57.358+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 17
    'start_date': datetime(2025,04,12)
                                ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2025-04-12T13:51:57.361+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:51:57.404+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.066 seconds
[2025-04-12T13:52:28.147+0000] {processor.py:186} INFO - Started process (PID=11933) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:52:28.149+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:52:28.153+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:52:28.152+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:52:28.164+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:52:28.161+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 17
    'start_date': datetime(2025,04,12)
                                ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2025-04-12T13:52:28.165+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:52:28.208+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.070 seconds
[2025-04-12T13:52:59.080+0000] {processor.py:186} INFO - Started process (PID=11996) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:52:59.082+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:52:59.087+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:52:59.086+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:52:59.096+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:52:59.095+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 17
    'start_date': datetime(2025,04,12)
                                ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2025-04-12T13:52:59.098+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:52:59.139+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.072 seconds
[2025-04-12T13:53:29.618+0000] {processor.py:186} INFO - Started process (PID=12061) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:53:29.620+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:53:29.623+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:53:29.622+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:53:29.630+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:53:29.629+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 17
    'start_date': datetime(2025,04,12)
                                ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2025-04-12T13:53:29.631+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:53:29.665+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.054 seconds
[2025-04-12T13:54:00.071+0000] {processor.py:186} INFO - Started process (PID=12125) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:54:00.073+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:54:00.076+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:54:00.076+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:54:00.084+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:54:00.083+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 17
    'start_date': datetime(2025,04,12)
                                ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2025-04-12T13:54:00.085+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:54:00.123+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.061 seconds
[2025-04-12T13:54:30.418+0000] {processor.py:186} INFO - Started process (PID=12190) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:54:30.425+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:54:30.434+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:54:30.434+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:54:30.455+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:54:30.452+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 17
    'start_date': datetime(2025,04,12)
                                ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2025-04-12T13:54:30.458+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:54:30.521+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.121 seconds
[2025-04-12T13:55:01.179+0000] {processor.py:186} INFO - Started process (PID=12254) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:55:01.182+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:55:01.186+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:55:01.185+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:55:01.196+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:55:01.194+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 17
    'start_date': datetime(2025,04,12)
                                ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2025-04-12T13:55:01.198+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:55:01.263+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.094 seconds
[2025-04-12T13:55:31.809+0000] {processor.py:186} INFO - Started process (PID=12320) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:55:31.812+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:55:31.817+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:55:31.816+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:55:31.830+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:55:31.828+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 17
    'start_date': datetime(2025,04,12)
                                ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2025-04-12T13:55:31.831+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:55:31.908+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.109 seconds
[2025-04-12T13:56:02.623+0000] {processor.py:186} INFO - Started process (PID=12385) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:56:02.625+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:56:02.628+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:56:02.628+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:56:02.637+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:56:02.635+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 17
    'start_date': datetime(2025,04,12)
                                ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2025-04-12T13:56:02.638+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:56:02.675+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.059 seconds
[2025-04-12T13:56:20.393+0000] {processor.py:186} INFO - Started process (PID=12428) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:56:20.396+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:56:20.404+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:56:20.403+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:56:20.428+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:56:20.425+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T13:56:20.429+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:56:20.484+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.104 seconds
[2025-04-12T13:56:21.680+0000] {processor.py:186} INFO - Started process (PID=12430) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:56:21.682+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:56:21.687+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:56:21.687+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:56:21.709+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:56:21.706+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T13:56:21.710+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:56:21.765+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.097 seconds
[2025-04-12T13:56:22.922+0000] {processor.py:186} INFO - Started process (PID=12432) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:56:22.924+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:56:22.928+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:56:22.927+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:56:22.945+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:56:22.942+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T13:56:22.947+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:56:22.994+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.083 seconds
[2025-04-12T13:56:53.068+0000] {processor.py:186} INFO - Started process (PID=12495) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:56:53.071+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:56:53.075+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:56:53.074+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:56:53.089+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:56:53.084+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T13:56:53.091+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:56:53.153+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.098 seconds
[2025-04-12T13:57:23.951+0000] {processor.py:186} INFO - Started process (PID=12558) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:57:23.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:57:23.960+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:57:23.959+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:57:23.971+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:57:23.968+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T13:57:23.973+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:57:24.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.073 seconds
[2025-04-12T13:57:54.400+0000] {processor.py:186} INFO - Started process (PID=12625) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:57:54.402+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:57:54.406+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:57:54.406+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:57:54.416+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:57:54.414+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T13:57:54.417+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:57:54.467+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.076 seconds
[2025-04-12T13:58:24.583+0000] {processor.py:186} INFO - Started process (PID=12689) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:58:24.585+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:58:24.588+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:58:24.588+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:58:24.598+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:58:24.596+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T13:58:24.600+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:58:24.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.068 seconds
[2025-04-12T13:58:55.403+0000] {processor.py:186} INFO - Started process (PID=12752) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:58:55.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:58:55.411+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:58:55.411+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:58:55.431+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:58:55.426+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T13:58:55.433+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:58:55.498+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.109 seconds
[2025-04-12T13:59:25.870+0000] {processor.py:186} INFO - Started process (PID=12816) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:59:25.872+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:59:25.876+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:59:25.876+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:59:25.890+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:59:25.886+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T13:59:25.892+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:59:25.949+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.089 seconds
[2025-04-12T13:59:56.248+0000] {processor.py:186} INFO - Started process (PID=12879) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T13:59:56.250+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T13:59:56.255+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:59:56.254+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T13:59:56.265+0000] {logging_mixin.py:190} INFO - [2025-04-12T13:59:56.262+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T13:59:56.266+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T13:59:56.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.071 seconds
[2025-04-12T14:00:26.636+0000] {processor.py:186} INFO - Started process (PID=12945) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:00:26.638+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:00:26.642+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:00:26.642+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:00:26.653+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:00:26.650+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:00:26.654+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:00:26.695+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.068 seconds
[2025-04-12T14:00:57.561+0000] {processor.py:186} INFO - Started process (PID=13010) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:00:57.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:00:57.568+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:00:57.567+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:00:57.578+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:00:57.576+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:00:57.579+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:00:57.624+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.072 seconds
[2025-04-12T14:01:27.905+0000] {processor.py:186} INFO - Started process (PID=13074) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:01:27.910+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:01:27.923+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:01:27.922+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:01:27.945+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:01:27.939+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:01:27.949+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:01:28.022+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.142 seconds
[2025-04-12T14:01:58.109+0000] {processor.py:186} INFO - Started process (PID=13138) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:01:58.112+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:01:58.119+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:01:58.118+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:01:58.131+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:01:58.128+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:01:58.133+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:01:58.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.090 seconds
[2025-04-12T14:02:28.343+0000] {processor.py:186} INFO - Started process (PID=13199) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:02:28.346+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:02:28.350+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:02:28.349+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:02:28.360+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:02:28.357+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:02:28.361+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:02:28.409+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.076 seconds
[2025-04-12T14:02:58.904+0000] {processor.py:186} INFO - Started process (PID=13264) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:02:58.906+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:02:58.911+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:02:58.910+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:02:58.923+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:02:58.919+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:02:58.924+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:02:58.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.087 seconds
[2025-04-12T14:03:29.707+0000] {processor.py:186} INFO - Started process (PID=13327) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:03:29.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:03:29.714+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:03:29.713+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:03:29.732+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:03:29.729+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:03:29.736+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:03:29.799+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.118 seconds
[2025-04-12T14:03:59.872+0000] {processor.py:186} INFO - Started process (PID=13390) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:03:59.874+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:03:59.882+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:03:59.882+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:03:59.904+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:03:59.901+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:03:59.906+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:03:59.953+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.093 seconds
[2025-04-12T14:04:30.107+0000] {processor.py:186} INFO - Started process (PID=13453) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:04:30.109+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:04:30.112+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:04:30.112+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:04:30.121+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:04:30.119+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:04:30.122+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:04:30.168+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.069 seconds
[2025-04-12T14:05:00.895+0000] {processor.py:186} INFO - Started process (PID=13518) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:05:00.898+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:05:00.904+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:05:00.903+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:05:00.917+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:05:00.913+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:05:00.919+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:05:00.996+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.112 seconds
[2025-04-12T14:05:14.088+0000] {processor.py:186} INFO - Started process (PID=13554) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:05:14.090+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:05:14.095+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:05:14.094+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:05:14.112+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:05:14.109+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:05:14.113+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:05:14.160+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.086 seconds
[2025-04-12T14:05:44.922+0000] {processor.py:186} INFO - Started process (PID=13618) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:05:44.924+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:05:44.928+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:05:44.928+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:05:44.939+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:05:44.936+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:05:44.940+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:05:44.984+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.069 seconds
[2025-04-12T14:06:15.457+0000] {processor.py:186} INFO - Started process (PID=13683) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:06:15.460+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:06:15.465+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:06:15.465+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:06:15.480+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:06:15.476+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:06:15.482+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:06:15.542+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.095 seconds
[2025-04-12T14:06:46.168+0000] {processor.py:186} INFO - Started process (PID=13747) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:06:46.169+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:06:46.174+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:06:46.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:06:46.186+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:06:46.183+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:06:46.187+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:06:46.237+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.095 seconds
[2025-04-12T14:07:16.454+0000] {processor.py:186} INFO - Started process (PID=13813) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:07:16.456+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:07:16.461+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:07:16.460+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:07:16.473+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:07:16.470+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:07:16.475+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:07:16.520+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.076 seconds
[2025-04-12T14:07:46.968+0000] {processor.py:186} INFO - Started process (PID=13876) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:07:46.970+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:07:46.973+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:07:46.972+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:07:46.982+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:07:46.979+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:07:46.983+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:07:47.018+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.059 seconds
[2025-04-12T14:08:17.214+0000] {processor.py:186} INFO - Started process (PID=13940) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:08:17.216+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:08:17.220+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:08:17.219+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:08:17.230+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:08:17.227+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:08:17.231+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:08:17.277+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.072 seconds
[2025-04-12T14:08:47.793+0000] {processor.py:186} INFO - Started process (PID=14004) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:08:47.796+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:08:47.803+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:08:47.803+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:08:47.825+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:08:47.818+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:08:47.828+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:08:47.894+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.113 seconds
[2025-04-12T14:09:18.086+0000] {processor.py:186} INFO - Started process (PID=14068) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:09:18.088+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:09:18.093+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:09:18.092+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:09:18.102+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:09:18.099+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:09:18.103+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:09:18.149+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.075 seconds
[2025-04-12T14:09:48.309+0000] {processor.py:186} INFO - Started process (PID=14133) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:09:48.311+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:09:48.316+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:09:48.316+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:09:48.326+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:09:48.323+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:09:48.328+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:09:48.375+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.078 seconds
[2025-04-12T14:10:18.674+0000] {processor.py:186} INFO - Started process (PID=14193) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:10:18.677+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:10:18.681+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:10:18.681+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:10:18.692+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:10:18.690+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:10:18.694+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:10:18.750+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.088 seconds
[2025-04-12T14:10:48.916+0000] {processor.py:186} INFO - Started process (PID=14259) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:10:48.919+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:10:48.925+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:10:48.924+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:10:48.937+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:10:48.934+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:10:48.939+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:10:48.993+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.091 seconds
[2025-04-12T14:11:19.530+0000] {processor.py:186} INFO - Started process (PID=14325) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:11:19.531+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:11:19.535+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:11:19.535+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:11:19.546+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:11:19.543+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:11:19.547+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:11:19.588+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.067 seconds
[2025-04-12T14:11:49.694+0000] {processor.py:186} INFO - Started process (PID=14388) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:11:49.696+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:11:49.700+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:11:49.699+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:11:49.715+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:11:49.710+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:11:49.718+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:11:49.789+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.105 seconds
[2025-04-12T14:12:19.894+0000] {processor.py:186} INFO - Started process (PID=14451) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:12:19.896+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:12:19.900+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:12:19.900+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:12:19.911+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:12:19.908+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:12:19.912+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:12:19.954+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.068 seconds
[2025-04-12T14:12:50.690+0000] {processor.py:186} INFO - Started process (PID=14515) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:12:50.692+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:12:50.698+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:12:50.698+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:12:50.713+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:12:50.709+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:12:50.715+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:12:50.765+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.087 seconds
[2025-04-12T14:13:20.849+0000] {processor.py:186} INFO - Started process (PID=14580) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:13:20.852+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:13:20.859+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:13:20.858+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:13:20.877+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:13:20.872+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:13:20.880+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:13:20.964+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.129 seconds
[2025-04-12T14:13:51.278+0000] {processor.py:186} INFO - Started process (PID=14646) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:13:51.282+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:13:51.286+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:13:51.285+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:13:51.296+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:13:51.293+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:13:51.297+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:13:51.347+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.077 seconds
[2025-04-12T14:14:21.521+0000] {processor.py:186} INFO - Started process (PID=14710) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:14:21.522+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:14:21.526+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:14:21.525+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:14:21.533+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:14:21.531+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:14:21.535+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:14:21.569+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.056 seconds
[2025-04-12T14:14:52.333+0000] {processor.py:186} INFO - Started process (PID=14774) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:14:52.335+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:14:52.339+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:14:52.339+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:14:52.348+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:14:52.346+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:14:52.351+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:14:52.400+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.076 seconds
[2025-04-12T14:15:22.802+0000] {processor.py:186} INFO - Started process (PID=14838) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:15:22.805+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:15:22.815+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:15:22.814+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:15:22.920+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:15:22.832+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:15:22.924+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:15:23.019+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.236 seconds
[2025-04-12T14:15:53.230+0000] {processor.py:186} INFO - Started process (PID=14900) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:15:53.232+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:15:53.238+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:15:53.237+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:15:53.255+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:15:53.251+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:15:53.257+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:15:53.328+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.116 seconds
[2025-04-12T14:16:23.788+0000] {processor.py:186} INFO - Started process (PID=14963) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:16:23.790+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:16:23.798+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:16:23.797+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:16:23.818+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:16:23.811+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:16:23.820+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:16:23.877+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.102 seconds
[2025-04-12T14:16:54.197+0000] {processor.py:186} INFO - Started process (PID=15026) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:16:54.200+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:16:54.204+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:16:54.204+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:16:54.216+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:16:54.214+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:16:54.218+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:16:54.272+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.085 seconds
[2025-04-12T14:17:24.653+0000] {processor.py:186} INFO - Started process (PID=15090) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:17:24.655+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:17:24.664+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:17:24.664+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:17:24.686+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:17:24.682+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:17:24.688+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:17:24.779+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.152 seconds
[2025-04-12T14:17:55.043+0000] {processor.py:186} INFO - Started process (PID=15155) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:17:55.045+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:17:55.049+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:17:55.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:17:55.059+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:17:55.056+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:17:55.060+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:17:55.115+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.081 seconds
[2025-04-12T14:18:25.515+0000] {processor.py:186} INFO - Started process (PID=15218) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:18:25.518+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:18:25.523+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:18:25.522+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:18:25.536+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:18:25.533+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:18:25.538+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:18:25.608+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.106 seconds
[2025-04-12T14:18:56.167+0000] {processor.py:186} INFO - Started process (PID=15283) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:18:56.171+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:18:56.179+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:18:56.178+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:18:56.207+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:18:56.201+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:18:56.210+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:18:56.303+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.162 seconds
[2025-04-12T14:19:26.459+0000] {processor.py:186} INFO - Started process (PID=15346) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:19:26.463+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:19:26.473+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:19:26.472+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:19:26.497+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:19:26.491+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:19:26.500+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:19:26.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.138 seconds
[2025-04-12T14:19:56.763+0000] {processor.py:186} INFO - Started process (PID=15406) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:19:56.767+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:19:56.775+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:19:56.775+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:19:56.793+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:19:56.787+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:19:56.795+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:19:56.860+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.112 seconds
[2025-04-12T14:20:26.958+0000] {processor.py:186} INFO - Started process (PID=15473) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:20:26.967+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:20:26.972+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:20:26.971+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:20:26.989+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:20:26.986+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:20:26.994+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:20:27.083+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.146 seconds
[2025-04-12T14:20:57.374+0000] {processor.py:186} INFO - Started process (PID=15536) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:20:57.376+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:20:57.381+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:20:57.380+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:20:57.392+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:20:57.389+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:20:57.394+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:20:57.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.078 seconds
[2025-04-12T14:21:30.190+0000] {processor.py:186} INFO - Started process (PID=15599) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:21:30.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:21:30.202+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:21:30.201+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:21:30.224+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:21:30.217+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:21:30.227+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:21:30.298+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.129 seconds
[2025-04-12T14:22:00.899+0000] {processor.py:186} INFO - Started process (PID=15661) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:22:00.920+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:22:00.928+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:22:00.927+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:22:00.949+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:22:00.943+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:22:00.951+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:22:01.039+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.175 seconds
[2025-04-12T14:22:31.377+0000] {processor.py:186} INFO - Started process (PID=15723) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:22:31.381+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:22:31.386+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:22:31.385+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:22:31.399+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:22:31.396+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:22:31.400+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:22:31.452+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.085 seconds
[2025-04-12T14:23:01.850+0000] {processor.py:186} INFO - Started process (PID=15793) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:23:01.852+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:23:01.856+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:23:01.855+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:23:01.866+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:23:01.864+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:23:01.867+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:23:01.942+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.101 seconds
[2025-04-12T14:23:32.658+0000] {processor.py:186} INFO - Started process (PID=15860) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:23:32.661+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:23:32.665+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:23:32.664+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:23:32.676+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:23:32.673+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:23:32.678+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:23:32.729+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.080 seconds
[2025-04-12T14:24:04.137+0000] {processor.py:186} INFO - Started process (PID=15924) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:24:04.141+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:24:04.151+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:24:04.150+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:24:04.191+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:24:04.181+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:24:04.199+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:24:04.299+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.182 seconds
[2025-04-12T14:24:34.461+0000] {processor.py:186} INFO - Started process (PID=15979) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:24:34.465+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:24:34.472+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:24:34.471+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:24:34.491+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:24:34.487+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:24:34.494+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:24:34.567+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.123 seconds
[2025-04-12T14:25:04.790+0000] {processor.py:186} INFO - Started process (PID=16043) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:25:04.792+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:25:04.797+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:25:04.796+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:25:04.808+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:25:04.806+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:25:04.810+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:25:04.861+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.079 seconds
[2025-04-12T14:25:35.814+0000] {processor.py:186} INFO - Started process (PID=16107) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:25:35.815+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:25:35.819+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:25:35.819+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:25:35.827+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:25:35.825+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:25:35.828+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:25:35.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.058 seconds
[2025-04-12T14:26:06.436+0000] {processor.py:186} INFO - Started process (PID=16167) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:26:06.438+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:26:06.443+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:26:06.442+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:26:06.454+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:26:06.451+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:26:06.456+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:26:06.497+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.070 seconds
[2025-04-12T14:26:36.866+0000] {processor.py:186} INFO - Started process (PID=16232) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:26:36.870+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:26:36.874+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:26:36.874+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:26:36.887+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:26:36.883+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:26:36.889+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:26:36.945+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.090 seconds
[2025-04-12T14:27:07.456+0000] {processor.py:186} INFO - Started process (PID=16297) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:27:07.459+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:27:07.464+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:27:07.463+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:27:07.475+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:27:07.472+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:27:07.476+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:27:07.537+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.091 seconds
[2025-04-12T14:27:37.971+0000] {processor.py:186} INFO - Started process (PID=16361) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:27:37.973+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:27:37.977+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:27:37.976+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:27:37.988+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:27:37.984+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:27:37.991+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:27:38.032+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.075 seconds
[2025-04-12T14:28:08.618+0000] {processor.py:186} INFO - Started process (PID=16426) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:28:08.620+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:28:08.623+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:28:08.623+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:28:08.634+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:28:08.631+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:28:08.635+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:28:08.678+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.069 seconds
[2025-04-12T14:28:38.896+0000] {processor.py:186} INFO - Started process (PID=16489) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:28:38.900+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:28:38.912+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:28:38.909+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:28:38.932+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:28:38.925+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:28:38.934+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:28:38.995+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.134 seconds
[2025-04-12T14:29:09.244+0000] {processor.py:186} INFO - Started process (PID=16552) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:29:09.245+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:29:09.249+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:29:09.248+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:29:09.257+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:29:09.255+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:29:09.258+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:29:09.296+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.059 seconds
[2025-04-12T14:29:40.188+0000] {processor.py:186} INFO - Started process (PID=16618) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:29:40.190+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:29:40.194+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:29:40.193+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:29:40.203+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:29:40.201+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:29:40.205+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:29:40.251+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.074 seconds
[2025-04-12T14:30:11.181+0000] {processor.py:186} INFO - Started process (PID=16684) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:30:11.183+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:30:11.186+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:30:11.186+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:30:11.197+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:30:11.194+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:30:11.198+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:30:11.256+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.086 seconds
[2025-04-12T14:30:41.834+0000] {processor.py:186} INFO - Started process (PID=16749) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:30:41.836+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:30:41.841+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:30:41.840+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:30:41.852+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:30:41.850+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:30:41.854+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:30:41.912+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.090 seconds
[2025-04-12T14:31:12.063+0000] {processor.py:186} INFO - Started process (PID=16815) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:31:12.064+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:31:12.069+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:31:12.069+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:31:12.078+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:31:12.076+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:31:12.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:31:12.118+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.063 seconds
[2025-04-12T14:31:43.064+0000] {processor.py:186} INFO - Started process (PID=16880) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:31:43.065+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:31:43.069+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:31:43.068+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:31:43.077+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:31:43.075+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:31:43.078+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:31:43.116+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.060 seconds
[2025-04-12T14:32:13.431+0000] {processor.py:186} INFO - Started process (PID=16947) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:32:13.434+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:32:13.440+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:32:13.439+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:32:13.458+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:32:13.449+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:32:13.461+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:32:13.533+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.112 seconds
[2025-04-12T14:32:44.281+0000] {processor.py:186} INFO - Started process (PID=17017) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:32:44.283+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:32:44.287+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:32:44.287+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:32:44.297+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:32:44.295+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:32:44.299+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:32:44.344+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.072 seconds
[2025-04-12T14:33:14.489+0000] {processor.py:186} INFO - Started process (PID=17082) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:33:14.491+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:33:14.495+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:33:14.495+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:33:14.505+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:33:14.502+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:33:14.506+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:33:14.545+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.068 seconds
[2025-04-12T14:33:44.611+0000] {processor.py:186} INFO - Started process (PID=17146) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:33:44.613+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:33:44.619+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:33:44.618+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:33:44.628+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:33:44.626+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:33:44.630+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:33:44.689+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.088 seconds
[2025-04-12T14:34:14.803+0000] {processor.py:186} INFO - Started process (PID=17212) to work on /opt/airflow/dags/pipeline.py
[2025-04-12T14:34:14.804+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline.py for tasks to queue
[2025-04-12T14:34:14.809+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:34:14.808+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline.py
[2025-04-12T14:34:14.818+0000] {logging_mixin.py:190} INFO - [2025-04-12T14:34:14.816+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline.py", line 2, in <module>
    from airflow.operator.python_operator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operator'
[2025-04-12T14:34:14.819+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline.py
[2025-04-12T14:34:14.851+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline.py took 0.056 seconds
